name: CI by push

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Clone repository
      uses: actions/checkout@v3
      with:
        repository: dryabokon/tools
        path: tools/

    - name: unit tests
      run: |
        python tests/test_00_Boundary_Tests.py > log.txt
        python tests/test_00_Boundary_Tests.py >>log.txt 2>&1

    - name: Upload logs
      uses: actions/upload-artifact@v3
      with:
        name: log
        path: log.txt